name: bandspace_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.4.0+7

environment:
  sdk: ^3.8.1

dependencies:
  just_audio: ^0.10.4
  connectivity_plus: ^6.1.4
  crypto: ^3.0.6
  dio: ^5.8.0+1
  equatable: ^2.0.7
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_secure_storage: ^9.2.4
  gap: ^3.0.1
  google_sign_in: ^7.1.1
  icons_plus: ^5.0.0
  intl: ^0.20.2
  lucide_icons_flutter: ^3.0.6
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  rxdart: ^0.28.0
  sembast: ^3.8.5
  shared_preferences: ^2.5.3
  sqflite: ^2.3.3
  package_info_plus: ^9.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  wakelock_plus: ^1.4.0
  sentry_flutter: ^9.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.local
